[features]
seeds = false
skip-lint = false

[programs.devnet]
observator_escrow = "6yXXYuix6c93kfGhqv8fCseRa7pXTKx1pxCjcFeWToPx"

[programs.mainnet]
observator_escrow = "11111111111111111111111111111111"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t ./tests/**/*.ts"
